<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<!-- ================= PROJECT INFORMATION ================== -->
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.xresch</groupId>
	<artifactId>xrutils-advanced</artifactId>
	<version>1.1.3</version>
	
	<name>XRUtils</name>
	<description>Library of various useful stuff.</description>
	<url>https://github.com/xresch/XRUtils</url>

	<!-- ================= PROPERTIES ================== -->
	<properties>
		
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<skipJavadoc>false</skipJavadoc>
		<skipTests>true</skipTests>
		<skipSigning>false</skipSigning>
	</properties>
	
		<!-- ================= LICENSES ================== -->
	<licenses>
		<license>
			<name>MIT License</name>
			<url>https://github.com/xresch/XRUtils/blob/main/LICENSE</url>
		</license>
	</licenses>

	<!-- ================= DEVELOPERS ================== -->
	<developers>
		<developer>
			<name>Reto Scheiwiller</name>
			<email>reto.scheiwiller5@bluewin.ch</email>
			<organization>xresch</organization>
			<organizationUrl>http://www.xresch.com</organizationUrl>
		</developer>
	</developers>

	<!-- ================= SCM ================== -->
	<scm>
		<connection>scm:git:git://github.com/xresch/XRUtils.git</connection>
		<developerConnection>scm:git:ssh://github.com/xresch/XRUtils.git</developerConnection>
		<url>https://github.com/xresch/XRUtils/tree/main</url>
	</scm>

	<!-- ================= DEPENDENCIES ================== -->
	<dependencies>
	
		<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
		<dependency>
		    <groupId>com.xresch</groupId>
		    <artifactId>xrutils</artifactId>
		    <version>1.1.3</version>
		</dependency>
		
		
		
		<!-- ========================================================================== -->
		<!-- ============================ SCOPE: TESTING ============================== -->
		<!-- ========================================================================== -->
		
		<!-- https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher -->
		<dependency>
		    <groupId>org.junit.platform</groupId>
		    <artifactId>junit-platform-launcher</artifactId>
		    <version>1.8.2</version>
		    <scope>provided</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>5.7.2</version>
			<scope>provided</scope>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.7.2</version>
			<scope>provided</scope>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.junit.platform/junit-platform-commons -->
		<dependency>
		    <groupId>org.junit.platform</groupId>
		    <artifactId>junit-platform-commons</artifactId>
		    <version>1.8.2</version>
		    <scope>provided</scope>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite-api -->
		<dependency>
		    <groupId>org.junit.platform</groupId>
		    <artifactId>junit-platform-suite-api</artifactId>
		    <version>1.8.2</version>
		    <scope>provided</scope>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite-engine -->
		<dependency>
		    <groupId>org.junit.platform</groupId>
		    <artifactId>junit-platform-suite-engine</artifactId>
		    <version>1.8.2</version>
		    <scope>provided</scope>
		</dependency>
		

	</dependencies>


	<!-- ================= BUILD ================== -->
	<build>
		
		<!-- ================= RESOURCES ================== -->
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		
		<!-- ================= TEST RESOURCES ================== -->
		<testResources>
			<testResource>
				<directory>src/test/java</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</testResource>
		</testResources>

		<plugins>
			<!-- ================= COMPILER ================== -->
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>17</source>
					<target>17</target>
				</configuration>
			</plugin>
			
			<!-- ================= INSTALL ================== -->
			<plugin>
			  <artifactId>maven-install-plugin</artifactId>
			  <version>2.3.1</version>
			  <configuration>
			    <createChecksum>true</createChecksum>
			  </configuration>
			</plugin>
			
			
			<!-- ================= SOURCES ================== -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.3.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<!-- ================= SUREFIRE ================== -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.5.4</version>
				<configuration>
					<skipTests>${skipTests}</skipTests>
					<includes>
						<include>**/*TestSuiteAll.java</include>
					</includes>
					<!-- excludes> <exclude>com.xresch.cfw.tests._master.*</exclude> </excludes -->
				</configuration>
			</plugin>

			<!-- ================= JAVADOC ================== -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<skip>${skipJavadoc}</skip>
					<additionalparam>-Xdoclint:none</additionalparam>
					<additionalOptions>-Xdoclint:none</additionalOptions>
					<additionalJOption>-Xdoclint:none</additionalJOption>
				</configuration>
			</plugin>
			
			<!-- ================= GPG SIGN ================== -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>1.6</version>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<skip>${skipSigning}</skip>
					<gpgArguments>
						<arg>--pinentry-mode</arg>
						<arg>loopback</arg>
						<arg>--status-fd</arg>
						<arg>--yes</arg>
						<arg>--always-trust</arg>

					</gpgArguments>
				</configuration>
			</plugin>
			
		</plugins>

	</build>
</project>